App\Entity\User: 
  attributes:
    normalization_context:
      groups: ["read"]
    denormalization_context:
      groups: ["user:write"]
  collectionOperations: [POST]
  itemOperations: [GET,  PUT]